### ISSUE TITLE
Installing bundles with a GitHub username/repo pair is not functioning

### ISSUE THREAD

**Issue by inkfarer** [nodecg/nodecg-cli#89]
Pulling git repositories using the `git://` protocol has been disabled by GitHub, causing nodecg-cli to be unable to install bundles by a username/repo pair. [Blog post from GitHub on the change](https://github.blog/2021-09-01-improving-git-protocol-security-github/)

### How to reproduce

Running on:
- macOS 12.2.1
- nodecg-cli version 8.0.0
- git version 2.34.0
- Node version 16.13.1

The following commands will throw an error:
`nodecg install speedcontrol/nodecg-speedcontrol`
`nodecg install inkfarer/ipl-overlay-controls`

Full log:
```
Fetching nodecg-speedcontrol release list... fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
failed!
Error: Command failed: git ls-remote --refs --tags git://github.com/speedcontrol/nodecg-speedcontrol.git
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at Object.default_1 [as default] (/usr/local/lib/node_modules/nodecg-cli/dist/lib/fetch-tags.js:5:37)
    at Command.action (/usr/local/lib/node_modules/nodecg-cli/dist/commands/install.js:53:36)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:1002:14)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:953:18)
    at Command._parseCommand (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:970:12)
    at Command.parse (/usr/local/lib/node_modules/nodecg-cli/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodecg-cli/dist/index.js:37:9)
```

**Comment by inkfarer** [comment]
Looks to be good now on nodecg-cli version 8.0.1. Thanks to everybody who helped me with releasing a fix!
